name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main # or whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .devcontainer/requirements.txt

      - name: Build site
        run: pelican content -o output -s pelicanconf.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./output
          publish_branch: main
          external_repository: tillg/test.grtnr.com
          cname: test.grtnr.com
