name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .devcontainer/requirements.txt

      - name: Set site name based on branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "PELICAN_SITENAME=grtnr.com" >> $GITHUB_ENV
          else
            echo "PELICAN_SITENAME=test.grtnr.com" >> $GITHUB_ENV
          fi

      - name: Build site
        run: inv preview
        
      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-output
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site-output
          path: ./output
          
      - name: Deploy to grtnr.com
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          publish_dir: ./output
          publish_branch: main
          external_repository: tillg/grtnr.com
          cname: grtnr.com
      
      - name: Deploy to test.grtnr.com
        if: github.ref != 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          publish_dir: ./output
          publish_branch: main
          external_repository: tillg/test.grtnr.com
          cname: test.grtnr.com